### ISSUE TITLE
Cant execute python scripts

### ISSUE THREAD

**Issue by julian-di** [10clouds/aiconsole#144]
## Expected Behavior

Dynamic documents work as expected

## Actual Behavior

I get python errors even when i run the app as admin

## Steps to Reproduce the Problem

1. Open any materials / dynamic document

## Specifications

- Version: latest (AIConsole-0.2.1-alpha30)
- Platform: Windows 11

![image](https://github.com/10clouds/aiconsole/assets/71697374/31352807-248c-422e-a643-f63009324fb6)

Stack trace as code:

```makrdown
Traceback (most recent call last):
  File "C:\Users\Julian\AppData\Local\AIConsole\app-0.2.1-alpha30\resources\python\lib\site-packages\aiconsole\core\assets\materials\material.py", line 131, in render
    "available_packages": get_current_project_venv_available_packages(),
  File "C:\Users\Julian\AppData\Local\AIConsole\app-0.2.1-alpha30\resources\python\lib\site-packages\aiconsole\core\project\venv.py", line 40, in get_current_project_venv_available_packages
    output = subprocess.check_output([str(get_current_project_venv_python_path() / "pip"), "list"]).decode("utf-8")
  File "C:\Users\Julian\AppData\Local\AIConsole\app-0.2.1-alpha30\resources\python\lib\subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\Julian\AppData\Local\AIConsole\app-0.2.1-alpha30\resources\python\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Julian\AppData\Local\AIConsole\app-0.2.1-alpha30\resources\python\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Julian\AppData\Local\AIConsole\app-0.2.1-alpha30\resources\python\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
```

**Comment by julian-di** [comment]
Sorry i did not see the closed issue :) already fixed as of https://github.com/10clouds/aiconsole/issues/141
