### ISSUE TITLE
Windows issues  [ACD-786]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#233]
Migrated from issue: [ACD-786](https://10clouds.atlassian.net/browse/ACD-786) (Bug)

Following scenario caused the console to go into rabbit hole of trying to install a python package, even though the Writer told me he can do it directly:,So as far I can see there are two possible problems here: ,Update 1:,Maybe it’s related, maybe not, but trying to get preview for some materials (like “List of Agents”) causes this error:,Traceback (most recent call last):
  File "C:\Users\radoslawlitman\AppData\Local\AIConsole\app-0.2.1-alpha30\resources\python\lib\site-packages\aiconsole\core\assets\materials\material.py", line 131, in render
    "available_packages": get_current_project_venv_available_packages(),
  File "C:\Users\radoslawlitman\AppData\Local\AIConsole\app-0.2.1-alpha30\resources\python\lib\site-packages\aiconsole\core\project\venv.py", line 40, in get_current_project_venv_available_packages
    output = subprocess.check_output([str(get_current_project_venv_python_path() / "pip"), "list"]).decode("utf-8")
  File "C:\Users\radoslawlitman\AppData\Local\AIConsole\app-0.2.1-alpha30\resources\python\lib\subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\radoslawlitman\AppData\Local\AIConsole\app-0.2.1-alpha30\resources\python\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\radoslawlitman\AppData\Local\AIConsole\app-0.2.1-alpha30\resources\python\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\radoslawlitman\AppData\Local\AIConsole\app-0.2.1-alpha30\resources\python\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Nie można odnaleźć określonego pliku
 

[ACD-786]: https://10clouds.atlassian.net/browse/ACD-786?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by pbaranski9411** [comment]
To devops: Where to test things on windows?

**Comment by aga-gasinska** [comment]
Wirtual machines with Windows to be provided to enable testing on iOS

**Comment by udislau** [comment]
Outdated, probably was fixed after rework of materials.
