### ISSUE TITLE
Chat error on simple arithmetics

### ISSUE THREAD

**Issue by udislau** [10clouds/aiconsole#549]
Input to chat:
`-2 + 88 - 1`

Log:
```shell
2024-01-08 12:19:08,401 aiconsole.api.endpoints.ws [DEBUG] Received message: {'type': 'InitChatMutationClientMessage', 'request_id': '0209ba6e-8c17-4e0b-bffe-7d2460c32c50', 'chat_id': '797ce100-9781-42a2-a6b7-0eea1dbbed2e', 'mutation': {'type': 'CreateMessageMutation', 'message_id': 'ed1cd1b1-ef62-4570-bbe2-775fadb64abf', 'message_group_id': '1d9efd7d-b251-4dfc-86c6-c152ee888234', 'content': '-2 + 88 - 1', 'timestamp': '2024-01-08T11:19:08.376Z'}}
2024-01-08 12:19:08,402 aiconsole.api.websockets.handle_incoming_message [INFO] Handling message InitChatMutationClientMessage
2024-01-08 12:19:08,404 aiconsole.api.endpoints.ws [DEBUG] Waiting for message
2024-01-08 12:19:08,414 aiconsole.api.endpoints.ws [DEBUG] Received message: {'type': 'ReleaseLockClientMessage', 'request_id': '0209ba6e-8c17-4e0b-bffe-7d2460c32c50', 'chat_id': '797ce100-9781-42a2-a6b7-0eea1dbbed2e'}
2024-01-08 12:19:08,415 aiconsole.api.websockets.handle_incoming_message [INFO] Handling message ReleaseLockClientMessage
2024-01-08 12:19:08,427 aiconsole.api.endpoints.ws [DEBUG] Waiting for message
2024-01-08 12:19:08,448 uvicorn.access [INFO] 127.0.0.1:65482 - "GET /profile HTTP/1.1" 200
2024-01-08 12:19:08,452 uvicorn.access [INFO] 127.0.0.1:65484 - "POST /commands/history HTTP/1.1" 200
2024-01-08 12:19:08,465 uvicorn.access [INFO] 127.0.0.1:65482 - "GET /profile HTTP/1.1" 200
2024-01-08 12:19:08,476 uvicorn.access [INFO] 127.0.0.1:65482 - "GET /profile HTTP/1.1" 200
2024-01-08 12:19:08,495 uvicorn.access [INFO] 127.0.0.1:65482 - "GET /profile HTTP/1.1" 200
2024-01-08 12:19:08,515 aiconsole.api.endpoints.ws [DEBUG] Received message: {'type': 'ProcessChatClientMessage', 'request_id': '125b17aa-a7c9-4a9f-b10f-7b829945ef8d', 'chat_id': '797ce100-9781-42a2-a6b7-0eea1dbbed2e'}
2024-01-08 12:19:08,515 aiconsole.api.websockets.handle_incoming_message [INFO] Handling message ProcessChatClientMessage
2024-01-08 12:19:08,516 aiconsole.core.chat.locking [DEBUG] Acquiring lock 797ce100-9781-42a2-a6b7-0eea1dbbed2e 125b17aa-a7c9-4a9f-b10f-7b829945ef8d
2024-01-08 12:19:08,519 aiconsole.core.chat.execution_modes.director [DEBUG] execution_mode_director
2024-01-08 12:19:08,551 aiconsole.core.gpt.gpt_executor [INFO] Executing GPT request:
2024-01-08 12:19:08,727 uvicorn.access [INFO] 127.0.0.1:65486 - "GET /profile_image?img_filename=user.jpg HTTP/1.1" 200
2024-01-08 12:19:08,728 uvicorn.access [INFO] 127.0.0.1:65482 - "GET /profile HTTP/1.1" 200
2024-01-08 12:19:08,743 uvicorn.access [INFO] 127.0.0.1:65482 - "GET /profile HTTP/1.1" 200
2024-01-08 12:19:13,334 uvicorn.access [INFO] 127.0.0.1:65486 - "GET /api/agents//image HTTP/1.1" 404
2024-01-08 12:19:13,710 aiconsole.core.chat.execution_modes.analysis.gpt_analysis_function_step [DEBUG] Chosen agent: id='automator' name='Automator' version='0.0.1' usage='When you need to execute code in order to calculate something, access access real-time data, connect to API, perform an action etc. You can use this if one one subtask is creating content, but it requires doing something with it in a programatic way.' usage_examples=[] defined_in=<AssetLocation.AICONSOLE_CORE: 'aiconsole'> type=<AssetType.AGENT: 'agent'> default_status=<AssetStatus.ENABLED: 'enabled'> status=<AssetStatus.ENABLED: 'enabled'> override=False system="You are a robotic Automator, capable of executing code to complete any task.\nYou employ an efficient and task-oriented tone, focusing on automation and streamlining processes to maximize productivity.\nWhen you send a message containing Python code to python, it will be executed in a stateful Jupyter notebook environment.\nPython will respond with the output of the execution.\nThe code you execute, will be executed on user's local environment, you have full access to the file system.\nThe code will have full internet access.\nYou can install packages.\nYour code can do *everything*.\nExecute code instead of asking the user to do something.\nNever ask for my permission to do things, I can always stop you if I want. Ask me to clarify if faced with ambiguity." gpt_mode=<GPTMode.QUALITY: 'quality'> execution_mode='aiconsole.core.chat.execution_modes.interpreter:execution_mode'
2024-01-08 12:19:13,728 aiconsole.core.gpt.gpt_executor [INFO] Executing GPT request:
2024-01-08 12:19:16,316 aiconsole.api.endpoints.ws [ERROR] argument of type 'int' is not iterable
Traceback (most recent call last):
  File "/Users/vlad/Documents/dev/10clouds/aiconsole/backend/aiconsole/api/endpoints/ws.py", line 47, in websocket_endpoint
    await handle_incoming_message(connection, json_data)
  File "/Users/vlad/Documents/dev/10clouds/aiconsole/backend/aiconsole/api/websockets/handle_incoming_message.py", line 101, in handle_incoming_message
    return await handler(connection, json)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vlad/Documents/dev/10clouds/aiconsole/backend/aiconsole/api/websockets/handle_incoming_message.py", line 243, in _handle_process_chat_ws_message
    await execution_mode.process_chat(
  File "/Users/vlad/Documents/dev/10clouds/aiconsole/backend/aiconsole/core/chat/execution_modes/director.py", line 110, in execution_mode_process
    await execution_mode.process_chat(context)
  File "/Users/vlad/Documents/dev/10clouds/aiconsole/backend/aiconsole/core/chat/execution_modes/interpreter.py", line 112, in _execution_mode_process
    await _generate_response(message_group, context, system_message, executor)
  File "/Users/vlad/Documents/dev/10clouds/aiconsole/backend/aiconsole/core/chat/execution_modes/interpreter.py", line 328, in _generate_response
    if arguments and "code" in arguments:
                     ^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'int' is not iterable
```

**Comment by udislau** [comment]
Change of temperature that was done in #651 potentially resolves the issue. 

Additionally, I will use testing framework to verify if the error is still present.
